<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- Current target -->
        <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Serchugar.Base.Shared</RootNamespace>

        <!-- NuGet packaging -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>false</IncludeSymbols>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- Package Version -->
        <PackageId>Serchugar.Base.Shared</PackageId>
        <Version>0.1.0-preview.1</Version>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>

        <!-- Visible metadata in nuget.org -->
        <Title>Base Shared</Title>
        <Description>
            Shared classes for other Serchugar.Base packages;.
        </Description>
        <PackageReleaseNotes>
            Moved Response&lt;T&gt; from Serchugar.Base.Backend and added IPrimaryKey static class.
        </PackageReleaseNotes>
        <PackageProjectUrl>https://github.com/serchugar/Base/tree/dev</PackageProjectUrl>
        <RepositoryUrl>https://github.com/serchugar/Base/tree/dev</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>Serchugar</Authors>
        <PackageTags>backend;repository;controller;response;generic</PackageTags>
    </PropertyGroup>

    <!-- Same README and LICENSE as in github repo -->
    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="" />
        <None Include="..\LICENSE" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>