<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- Current target -->
        <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Serchugar.Base.Backend</RootNamespace>
        
        <Configurations>Shared;Backend;Tests</Configurations>
        <Platforms>AnyCPU</Platforms>

        <!-- NuGet packaging -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>false</IncludeSymbols>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- Package Version -->
        <PackageId>Serchugar.Base.Backend</PackageId>
        <Version>0.1.0-preview.4</Version>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>

        <!-- Visible metadata in nuget.org -->
        <Title>Base Backend</Title>
        <Description>
            Generic base classes for Repository service, Controller and Response&lt;T&gt;.
        </Description>
        <PackageReleaseNotes>
            Added Guid overload for GetById and Delete in BaseRepository.cs. 
            Added XML comments to everything. 
            Added ActionResult 200 OK for bulk create, update and delete operations.
        </PackageReleaseNotes>
        <PackageProjectUrl>https://github.com/serchugar/Base/tree/dev</PackageProjectUrl>
        <RepositoryUrl>https://github.com/serchugar/Base/tree/dev</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>Serchugar</Authors>
        <PackageTags>backend;repository;controller;response;generic</PackageTags>
    </PropertyGroup>
    
    <!-- Same README and LICENSE as in github repo -->
    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="" />
        <None Include="..\LICENSE" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
        <PackageReference Include="Serchugar.Base.Shared" Version="0.1.0-preview.2" />
    </ItemGroup>

</Project>
